### ISSUE TITLE
Segmentation Fault While Running Examples - Source Conda Install 

### ISSUE THREAD

**Issue by nkpng2k** [facebookresearch/TensorComprehensions#164] opened 2018-03-15 20:11 UTC
- OS: Ubuntu 16.04
- Installed via: Source Conda Env
- Python version: Python 3.6.3 :: Anaconda custom (64-bit)
- CUDA/cuDNN version: cudatoolkit 8.0 / cudnn 7.0.5 
- Conda version (if using conda): conda 4.4.11
- GCC/GXX version: gcc (Ubuntu 5.4.1-2ubuntu1~16.04) 5.4.1 20160904 / g++ (Ubuntu 5.4.1-2ubuntu1~16.04) 5.4.1 20160904
- LLVM/Tapir git hash used: 
$HOME/clang+llvm-tapir5.0/bin/clang --version
clang version 5.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/npng/clang+llvm-tapir5.0/bin

- Commit hash:
* master 25cbf22 Merge pull request #159 from facebookresearch/fix-docker-trusty

In addition, including the following information will also be very helpful for us to diagnose the problem:
- To build: I followed these instructions exactly: https://facebookresearch.github.io/TensorComprehensions/installation_conda.html
- Error messages and/or stack traces of the issue (create a gist)
https://gist.github.com/nkpng2k/a429732e8a09ae2f7459620b26b57f7c
python_example.py is the first example found here:
https://facebookresearch.github.io/TensorComprehensions/framework/pytorch_integration/writing_layers.html

Output from python client:
![screen shot 2018-03-15 at 12 09 25 pm](https://user-images.githubusercontent.com/29209863/37487541-0a974fda-284f-11e8-9313-ca60270cb22d.png)

- Trying to install Tensor Comprehensions and test it out. Running the examples provided in the docs returns: segmentation fault (core dumped)

**Comment by prigoyal** [comment] 2018-03-15 21:02
thanks @nkpng2k , the core dump could happen if the pytorch installation is not compatible with TC. Can you give information on how did you install pytorch?

**Comment by nkpng2k** [comment] 2018-03-15 21:09
@prigoyal 
Hi I ran this command:
conda install -c pytorch -c tensorcomp tensor_comprehensions

**Comment by prigoyal** [comment] 2018-03-15 21:49
thanks @nkpng2k for the info. can you try the following once and let me know if it works:
```
conda create -y --name tc-env python=3.6
source activate tc-env
conda install -c pytorch -c tensorcomp tensor_comprehensions
```

I believe that there is another pytorch install in your env PATH and that is colliding with the pytorch version TC is compatible with.

**Comment by nkpng2k** [comment] 2018-03-15 22:28
@prigoyal 

after creating a new environment, I tried running the example again. Same issue. So I deactivated the environment, used conda uninstall to remove pytorch and tensor_comprehensions. Reactivated the environment, can't import --> torch module not found. 

Reinstalled pytorch and tensor_comprehensions in the conda env, same issue.

**Comment by prigoyal** [comment] 2018-03-15 22:57
@nkpng2k can you show the log of the steps and the output of them?

can you also confirm if you executed the steps 
```
conda create -y --name tc-env python=3.6
source activate tc-env
conda install -c pytorch -c tensorcomp tensor_comprehensions
```
in the exact same order.

**Comment by nkpng2k** [comment] 2018-03-16 00:06
`npng@tensor-comp:~/TensorComprehensions$ conda create -y --name tc-env python=3.6
Solving environment: done

## Package Plan ##

  environment location: /home/npng/anaconda3/envs/tc-env

  added / updated specs:
    - python=3.6


The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-h1d4fec5_0
    certifi:         2018.1.18-py36_0
    libedit:         3.1-heed3624_0
    libffi:          3.2.1-hd88cf55_4
    libgcc-ng:       7.2.0-hdf63c60_3
    libstdcxx-ng:    7.2.0-hdf63c60_3
    ncurses:         6.0-h9df7e31_2
    openssl:         1.0.2n-hb7f436b_0
    pip:             9.0.1-py36_5
    python:          3.6.4-hc3d631a_3
    readline:        7.0-ha6073c6_4
    setuptools:      38.5.1-py36_0
    sqlite:          3.22.0-h1bed415_0
    tk:              8.6.7-hc745277_3
    wheel:           0.30.0-py36hfd4bba0_1
    xz:              5.2.3-h55aa19d_2
    zlib:            1.2.11-ha838bed_2

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use:
# > source activate tc-env
#
# To deactivate an active environment, use:
# > source deactivate
#

npng@tensor-comp:~/TensorComprehensions$ source activate tc-env
(tc-env) npng@tensor-comp:~/TensorComprehensions$ conda install -c pytorch -c tensorcomp tensor_comprehensions
Solving environment: done

## Package Plan ##

  environment location: /home/npng/anaconda3/envs/tc-env

  added / updated specs:
    - tensor_comprehensions


The following NEW packages will be INSTALLED:

    bzip2:                 1.0.6-h9a117a8_4
    cffi:                  1.11.5-py36h9745a5d_0
    cmake:                 3.9.4-h142f0e9_0
    cudatoolkit:           8.0-3
    cudnn:                 7.0.5-cuda8.0_0
    curl:                  7.58.0-h84994c4_0
    expat:                 2.2.5-he0dffb1_0
    gflags:                2.4.4-h4126541_2                   tensorcomp
    glog:                  0.3.9-h3408eea_2                   tensorcomp
    gmp:                   6.1.2-h6c8ec71_1
    halide:                0.1.0-h9df8326_2                   tensorcomp
    intel-openmp:          2018.0.0-hc7b2577_8
    isl-tc:                0.1.0-h9c8d533_2                   tensorcomp
    libcurl:               7.58.0-h1ad7b7a_0
    libgfortran-ng:        7.2.0-hdf63c60_3
    libssh2:               1.8.0-h9cfc8f7_4
    libuv:                 1.19.2-h14c3975_0
    llvm-tapir50:          0.1.0-h186cc49_2                   tensorcomp
    mkl:                   2018.0.1-h19d6760_4
    numpy:                 1.14.2-py36hdbf6ddf_0
    protobuf:              3.4.1-h21cfbc1_2                   tensorcomp
    pycparser:             2.18-py36hf9f622e_1
    pytorch:               0.3.1-py36_cuda8.0.61_cudnn7.0.5_2 pytorch
    pyyaml:                3.12-py36hafb9ca4_1
    rhash:                 1.3.5-hbf7ad62_1
    six:                   1.11.0-py36h372c433_1
    tensor_comprehensions: 0.1.1-hc1584b5_3                   tensorcomp
    unzip:                 6.0-h611a1e1_0
    yaml:                  0.1.7-had09818_2

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done`

**Comment by nkpng2k** [comment] 2018-03-16 00:07
```
npng@tensor-comp:~/TensorComprehensions$ conda create -y --name tc-env python=3.6
Solving environment: done

## Package Plan ##

  environment location: /home/npng/anaconda3/envs/tc-env

  added / updated specs:
    - python=3.6


The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-h1d4fec5_0
    certifi:         2018.1.18-py36_0
    libedit:         3.1-heed3624_0
    libffi:          3.2.1-hd88cf55_4
    libgcc-ng:       7.2.0-hdf63c60_3
    libstdcxx-ng:    7.2.0-hdf63c60_3
    ncurses:         6.0-h9df7e31_2
    openssl:         1.0.2n-hb7f436b_0
    pip:             9.0.1-py36_5
    python:          3.6.4-hc3d631a_3
    readline:        7.0-ha6073c6_4
    setuptools:      38.5.1-py36_0
    sqlite:          3.22.0-h1bed415_0
    tk:              8.6.7-hc745277_3
    wheel:           0.30.0-py36hfd4bba0_1
    xz:              5.2.3-h55aa19d_2
    zlib:            1.2.11-ha838bed_2

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use:
# > source activate tc-env
#
# To deactivate an active environment, use:
# > source deactivate
#

npng@tensor-comp:~/TensorComprehensions$ source activate tc-env
(tc-env) npng@tensor-comp:~/TensorComprehensions$ conda install -c pytorch -c tensorcomp tensor_comprehensions
Solving environment: done

## Package Plan ##

  environment location: /home/npng/anaconda3/envs/tc-env

  added / updated specs:
    - tensor_comprehensions


The following NEW packages will be INSTALLED:

    bzip2:                 1.0.6-h9a117a8_4
    cffi:                  1.11.5-py36h9745a5d_0
    cmake:                 3.9.4-h142f0e9_0
    cudatoolkit:           8.0-3
    cudnn:                 7.0.5-cuda8.0_0
    curl:                  7.58.0-h84994c4_0
    expat:                 2.2.5-he0dffb1_0
    gflags:                2.4.4-h4126541_2                   tensorcomp
    glog:                  0.3.9-h3408eea_2                   tensorcomp
    gmp:                   6.1.2-h6c8ec71_1
    halide:                0.1.0-h9df8326_2                   tensorcomp
    intel-openmp:          2018.0.0-hc7b2577_8
    isl-tc:                0.1.0-h9c8d533_2                   tensorcomp
    libcurl:               7.58.0-h1ad7b7a_0
    libgfortran-ng:        7.2.0-hdf63c60_3
    libssh2:               1.8.0-h9cfc8f7_4
    libuv:                 1.19.2-h14c3975_0
    llvm-tapir50:          0.1.0-h186cc49_2                   tensorcomp
    mkl:                   2018.0.1-h19d6760_4
    numpy:                 1.14.2-py36hdbf6ddf_0
    protobuf:              3.4.1-h21cfbc1_2                   tensorcomp
    pycparser:             2.18-py36hf9f622e_1
    pytorch:               0.3.1-py36_cuda8.0.61_cudnn7.0.5_2 pytorch
    pyyaml:                3.12-py36hafb9ca4_1
    rhash:                 1.3.5-hbf7ad62_1
    six:                   1.11.0-py36h372c433_1
    tensor_comprehensions: 0.1.1-hc1584b5_3                   tensorcomp
    unzip:                 6.0-h611a1e1_0
    yaml:                  0.1.7-had09818_2

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

**Comment by nkpng2k** [comment] 2018-03-16 00:07
@prigoyal ^

**Comment by prigoyal** [comment] 2018-03-16 12:14
thanks. I am not able to repro the segfault this way. Can you tell the output of below:
1. python -c 'import torch; print(torch)'
2. which python

**Comment by nkpng2k** [comment] 2018-03-16 16:43
Conda Env Not Activated:
```
npng@tensor-comp:~/TensorComprehensions$ python -c 'import torch; print(torch)'
<module 'torch' from '/home/npng/anaconda3/lib/python3.6/site-packages/torch/__init__.py'>
npng@tensor-comp:~/TensorComprehensions$ which python
/home/npng/anaconda3/bin/python
npng@tensor-comp:~/TensorComprehensions$ which ipython
/home/npng/anaconda3/bin/ipython
```

Conda Env Activated:
```
(tc-env) npng@tensor-comp:~/TensorComprehensions$ python -c 'import torch; print(torch)'
<module 'torch' from '/home/npng/anaconda3/envs/tc-env/lib/python3.6/site-packages/torch/__init__.py'>
(tc-env) npng@tensor-comp:~/TensorComprehensions$ which python
/home/npng/anaconda3/envs/tc-env/bin/python
(tc-env) npng@tensor-comp:~/TensorComprehensions$ which ipython
/home/npng/anaconda3/bin/ipython
```

**Comment by nkpng2k** [comment] 2018-03-16 16:43
@prigoyal ^

**Comment by stromnov** [comment] 2018-03-16 18:00
Same issue:

```
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensor_comprehensions as tc
>>> import torch
>>> lang = """
... def matmul(float(M,N) A, float(N,K) B) -> (output) {
...   output(i, j) +=! A(i, kk) * B(kk, j)
... }
... """
>>> matmul = tc.define(lang, name="matmul")
>>> mat1, mat2 = torch.randn(3, 4), torch.randn(4, 5)
>>> out = matmul(mat1, mat2)
[WARNING]: No mapping options passed, 'naive' type mapping options will be used and will likely have bad performance. See help(your_layer.__call__) for setting mapping options.
[New Thread 0x7fffb9284700 (LWP 10250)]

Program received signal SIGSEGV, Segmentation fault.
0x00007fffdf1fded6 in at::CPUFloatTensor* at::checked_cast_tensor<at::CPUFloatTensor, at::TensorImpl>(at::TensorImpl*, char const*, int, bool) [clone .constprop.92] ()
   from /home/ubuntu/anaconda3/envs/tc-build/lib/python3.6/site-packages/torch/lib/libATen.so.1
```

**Comment by ftynse** [comment] 2018-03-16 19:14
@stromnov your issue looks different; first thing -- you forgot `.cuda()` when creating tensors so they were not allocated on the gpu.

**Comment by stromnov** [comment] 2018-03-16 19:24
@ftynse: `.cuda()` was specially omitted just to be sure that problem not in CUDA drivers.

```
>>> import tensor_comprehensions as tc
>>> import torch
>>> lang = """
... def matmul(float(M,N) A, float(N,K) B) -> (output) {
...   output(i, j) +=! A(i, kk) * B(kk, j)
... }
... """
>>> matmul = tc.define(lang, name="matmul")
>>> mat1, mat2 = torch.randn(3, 4).cuda(), torch.randn(4, 5).cuda()
[New Thread 0x7fffb9284700 (LWP 11351)]
[New Thread 0x7fffb8a83700 (LWP 11352)]
>>> out = matmul(mat1, mat2)
[WARNING]: No mapping options passed, 'naive' type mapping options will be used and will likely have bad performance. See help(your_layer.__call__) for setting mapping options.

Program received signal SIGSEGV, Segmentation fault.
0x00007fffdf2ebe16 in at::CUDAFloatTensor* at::checked_cast_tensor<at::CUDAFloatTensor, at::TensorImpl>(at::TensorImpl*, char const*, int, bool) [clone .constprop.92] ()
   from /home/ubuntu/anaconda3/envs/tc-build/lib/python3.6/site-packages/torch/lib/libATen.so.1
```

```
>>> torch.__version__
'0.3.1b0+2b47480'```

**Comment by prigoyal** [comment] 2018-03-16 23:53
@stromnov , @nkpng2k can you provide some repro ? maybe a docker image etc?

**Comment by prigoyal** [comment] 2018-03-19 14:57
Hi @stromnov and @nkpng2k , I was thinking more about this and I was wondering if you have ever built pytorch from source? or were using other pytorch version before?

also, @nkpng2k , from can you run:
```
import torch
print(torch)
```
inside `ipython` interpretor and show me the result? thanks!

**Comment by stromnov** [comment] 2018-03-19 21:21
Sorry, I just don't know yet how to properly provide reproducible environment for that issue.

About pytorch: module was built from sources (tag v0.3.1) using tc-build anaconda environment. There are no other pytorch modules installed.

**Comment by prigoyal** [comment] 2018-03-20 17:10
thanks @stromnov , may I recommend that you use the conda install of pytorch rather than build from source. We don't provide official instructions for building pytorch from source and using with TC atm. Can you try and let me know if the conda install works fine? :)

**Comment by nkpng2k** [comment] 2018-03-21 16:58
@prigoyal This is what I have. 

```
npng@tensor-comp:~$ ipython
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch

In [2]: print(torch)
<module 'torch' from '/home/npng/anaconda3/lib/python3.6/site-packages/torch/__init__.py'>
```

**Comment by nkpng2k** [comment] 2018-03-22 00:52
@prigoyal I apologize. I forgot to start the conda env before that last comment, but that is not the issue. Ran again within the conda environment after running conda install ipython just to be sure.

```
(tc-env) npng@tensor-comp:~/TensorComprehensions$ ipython
Python 3.6.4 |Anaconda, Inc.| (default, Mar 13 2018, 01:15:57)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch

In [2]: print(torch)
<module 'torch' from '/home/npng/anaconda3/envs/tc-env/lib/python3.6/site-packages/torch/__init__.py'>

In [3]: import tensor_comprehensions as tc

In [4]: MATMUL_LANG = """
   ...: def matmul(float(M,N) A, float(N,K) B) -> (output) {
   ...:   output(i, j) +=! A(i, kk) * B(kk, j)
   ...: }
   ...: """

In [5]: matmul = tc.define(MATMUL_LANG, name="matmul")
   ...: mat1, mat2 = torch.randn(3, 4).cuda(), torch.randn(4, 5).cuda()
   ...: out = matmul(mat1, mat2)
   ...:
[WARNING]: No mapping options passed, 'naive' type mapping options will be used and will likely have bad performance. See help(your_layer.__call__) for setting mapping options.
Segmentation fault (core dumped)
(tc-env) npng@tensor-comp:~/TensorComprehensions$
```

**Comment by prigoyal** [comment] 2018-03-22 16:38
thanks @nkpng2k. We need to figure out the repro for this to find the issue. Can you try this inside docker environment and see if that works? I think the reason for segfault is that there is a different pytorch install that's getting picked up and is not compatible with the TC package. So  isolating the env and trying in docker file will help confirm that.

**Comment by yazdanbakhsh** [comment] 2018-03-23 09:09
I am getting the same segmentation fault. I have installed PyTorch with 
    conda install pytorch torchvision -c pytorch

**Comment by yazdanbakhsh** [comment] 2018-03-23 10:17
Tried nvidia-docker. Got segmentation fault again.

**Comment by prigoyal** [comment] 2018-03-23 13:42
@yazdanbakhsh this is great news. If the error is reproed in the docker env, we can start finding the root cause. Can you provide me the exact set of instructions that I can use to repro? Thanks.

**Comment by prigoyal** [comment] 2018-03-23 19:39
repro from the user here https://tensorcomprehensions.slack.com/files/U9EJ73BUH/F9V8DR150/The_commands_to_install_TensorFlow_in_docker__It_generates_a_segmentation_fault_.cpp

I'll repro this myself by following the exact same step as user and root-cause this. :)

**Comment by sidelnik** [comment] 2018-04-02 02:00
Would like to add that I am getting the exact same segfault errors as the users above. In my case I am trying with pytorch support for CUDA 9.1. I downloaded pytorch from `conda install pytorch torchvision cuda91 -c pytorch`

**Comment by prigoyal** [comment] 2018-04-02 13:03
Hi @sidelnik , thanks for reporting. Indeed for cuda9.1 and pytorch install, we do get the segfault. This shouldn't happen with cuda8 though. We plan to work on resolving the segfault with cuda9 and provide TC package working with that in our next release. There is an issue tracking it: https://github.com/facebookresearch/TensorComprehensions/issues/129

**Closed** 2020-05-16 01:21 UTC
Labels: awaiting-user-response, build
