### ISSUE TITLE
Autotuner aborts when tuning conv2d

### ISSUE THREAD

**Issue by merrymercy** [facebookresearch/TensorComprehensions#292] opened 2018-04-11 09:20 UTC
- OS: Ubuntu 16.04
- How you installed TC (docker, conda, source): source
- Python version: 3.5
- CUDA/cuDNN version: 9.1 / 7.1.2
- GCC/GXX version (if compiling from source): 5.4
- LLVM/Tapir git hash used (if compiling from source): 
clang version 5.0.0 
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/mercy/clang+llvm-tapir5.0/bin
- Commit hash of our repo and submodules (if compiling from source):
https://github.com/facebookresearch/TensorComprehensions/commit/ef644ba7d638f3f8b028f52192101cf1f48b32b4
- Hardware: crashed on both Titan X and 1050Ti

script 
```python
import numpy as np
import torch
import os

import tensor_comprehensions as tc

settings = {
    "threads": 8, "generations": 10, "pop_size": 100, "number_elites": 3
}

conv2d_lang = """
def conv2d(float(N, C, H, W) I, float(M, C, KH, KW) W1) -> (output) {{
    output(n, m, h, w) +=! I(n, c, {sh} * h + kh, {sw} * w + kw) * W1(m, c, kh, kw)
}}
"""

print(os.getpid())

N, H, C, M, KH, sh, pad = 1, 56, 64, 128, 3, 2, 1
H = H + 2 * pad
W = H
KW = KH
sw = sh

conv2d = tc.define(conv2d_lang, name="conv2d", constants={"sh": sh, "sw": sw})

options = tc.Options('conv')
data, kernel = torch.randn(N, C, H, W).cuda(), torch.randn(M, C, KH, KW).cuda()

conv2d.autotune(data, kernel, options=options, **settings)
```

output
```
[WARNING]: Autotuning results won't be cached. 'cache' option is not set
Generation 0	Jobs(Compiled, GPU)/total  (89, 81)/100   (best/median/worst)us: 1183/4122/56294WARNING: Logging before InitGoogleLogging() is written to STDERR
W0411 17:14:07.169371  6574 cuda_rtc.cc:144] Error at: /home/mercy/project/TensorComprehensions/src/core/cuda/cuda_rtc.cc:144: CUDA_ERROR_INVALID_PTX
W0411 17:14:07.169657  6574 genetic_tuning_harness.cc:415] Runtime error gpu 0: Error at: /home/mercy/project/TensorComprehensions/src/core/cuda/cuda_rtc.cc:144: CUDA_ERROR_INVALID_PTX
W0411 17:14:07.169761  6574 genetic_tuning_harness.cc:419] Aborted execution on gpu 0
W0411 17:14:07.169840  6574 genetic_tuning_harness.cc:420] tc::MappingOptions::makeNaiveMappingOptions()
W0411 17:14:07.169909  6574 genetic_tuning_harness.cc:420]     .outerScheduleFusionStrategy(tc::FusionStrategy::Preserve3Coincident)
W0411 17:14:07.169976  6574 genetic_tuning_harness.cc:420]     .outerScheduleAllowSkewing(false)
W0411 17:14:07.170042  6574 genetic_tuning_harness.cc:420]     .outerSchedulePositiveOrthant(true)
W0411 17:14:07.170109  6574 genetic_tuning_harness.cc:420]     .intraTileScheduleFusionStrategy(tc::FusionStrategy::Min)
W0411 17:14:07.170174  6574 genetic_tuning_harness.cc:420]     .intraTileScheduleAllowSkewing(false)
W0411 17:14:07.170239  6574 genetic_tuning_harness.cc:420]     .intraTileSchedulePositiveOrthant(true)
W0411 17:14:07.170306  6574 genetic_tuning_harness.cc:420]     .tile(8, 16, 1)
W0411 17:14:07.170372  6574 genetic_tuning_harness.cc:420]     .unroll(4)
W0411 17:14:07.170436  6574 genetic_tuning_harness.cc:420]     .tileImperfectlyNested(false)
W0411 17:14:07.170503  6574 genetic_tuning_harness.cc:420]     .matchLibraryCalls(true);
W0411 17:14:07.170569  6574 genetic_tuning_harness.cc:420] 
W0411 17:14:07.170635  6574 genetic_tuning_harness.cc:420]     .mapToThreads(29, 15)
W0411 17:14:07.170701  6574 genetic_tuning_harness.cc:420]     .mapToBlocks(3)
W0411 17:14:07.170769  6574 genetic_tuning_harness.cc:420]     .useSharedMemory(true)
W0411 17:14:07.170836  6574 genetic_tuning_harness.cc:420]     .usePrivateMemory(false)
W0411 17:14:07.170902  6574 genetic_tuning_harness.cc:420]     .unrollCopyShared(true);
Generation 0	Jobs(Compiled, GPU)/total  (100, 100)/100   (best/median/worst)us: 1183/4122/56294
W0411 17:14:27.770052  6564 cuda_rtc.cc:44] Error at: /home/mercy/project/TensorComprehensions/src/core/cuda/cuda_rtc.cc:44: CUDA_ERROR_INVALID_HANDLE
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error at: /home/mercy/project/TensorComprehensions/src/core/cuda/cuda_rtc.cc:44: CUDA_ERROR_INVALID_HANDLE
Aborted (core dump)
```

**Comment by ftynse** [comment] 2018-04-11 14:34
Invalid PTX may mean we request more shared memory than available due to reductions.  An equivalent C++ test completes fine on my machine (P6000).

@prigoyal is there a way to dump the cuda from python interface?

**Comment by ftynse** [comment] 2018-04-11 14:39
If somebody can run `./build/test/cuda/test_tc_mapper_bugs --gtest_filter=Convolution2D.InvalidPtx` on 582692d7b021a6a8c5ef755df7d25d5d6786d022 and confirm there is indeed an error, that would help.

**Comment by ttheodor** [comment] 2018-04-11 14:41
```
hammerhead% ./build/test/cuda/test_tc_mapper_bugs --gtest_filter=Convolution2D.InvalidPtx    remotes/origin/repro-292
Note: Google Test filter = Convolution2D.InvalidPtx
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Convolution2D
[ RUN      ] Convolution2D.InvalidPtx
[       OK ] Convolution2D.InvalidPtx (3745 ms)
[----------] 1 test from Convolution2D (3745 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (3745 ms total)
[  PASSED  ] 1 test.
```

**Comment by ftynse** [comment] 2018-04-11 15:01
I got a different one with the autotuner, though.

**Comment by prigoyal** [comment] 2018-04-11 15:41
@ftynse , yes there is a way to dump cuda from python interface. See this example https://github.com/facebookresearch/TensorComprehensions/blob/master/test_python/test_debug_init.py#L22

**Comment by ftynse** [comment] 2018-04-11 18:41
Indeed, the problem is only manifest _during the autotuning_, and only on some runs.  I had to run 6 independent turns of 25x100 iterations to reproduce it.  However, taking the offending options reported by the autotuner and putting them in a separate test _works fine_.

I may suspect:
- offending options are reported incorrectly;
- problems with allocation/reusing the same tensor;
- concurrency problems in the autotuner.

casting @ttheodor and @nicolasvasilache in this thread

**Comment by ftynse** [comment] 2018-04-11 21:08
Pushed d506fed756cff67bbafd72052423adbc1dc9033c with the autotuner call on the same test. Everybody's welcome to try and get a stable repro.

**Comment by ftynse** [comment] 2018-04-12 11:32
I may have identified the problem for the `INVALID_HANDLE` crash part, but not the source of the problem for `INVALID_PTX` and memory corruptions that were also observed.

In `CudaRTCFunction::Launch`, we first add (empty) module to the per-GPU list of modules, and only then try to load it from PTX.  The load part may fail and throw, the module in the list remaining empty.  When the `CudaRTCFunction` is destroyed, its destructor tries to unload the module available in the list.  Since the module is empty, unloading fails and throws. The exception does not seem to be handled, and can even happen during unwinding of another exception leading to immediate termination.

**Comment by ftynse** [comment] 2018-04-12 11:37
#299 should remove the `INVALID_HANDLE` part and let the autotuning continue.

I still don't have a reproduction for the invalid PTX issue, but that may be platform-specific.

**Comment by ftynse** [comment] 2018-04-12 13:00
#299 indeed prevents the crash on "invalid PTX" error.  The error will be reported, but the tuning will continue after discarding the options that caused the error.  Merging that PR will close this issue.

In the meantime, I have a stable reproducer of "invalid PTX".  As I expected, it is indeed caused by requiring too much shared memory, so the reproducibility depends on the GPU model in use.  I will open a separate issue for that.

**Comment by ftynse** [comment] 2018-04-12 13:14
#300 for the new reductions issue

**Closed** 2018-04-12 13:25 UTC
